<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Promise</title>
</head>
<body>
    <script>
        // 使用Promise(mdn)
        // Promise是一个对象，它代表了一个异步操作的最终完成或者失败。
        // 三个状态：
        // 待定（pending）：初始状态，即没有被兑现，也没有被拒绝
        // 已兑现（fulfilled）：意味着操作成功完成。
        // 已拒绝（rejected）：意味着操作失败。

        // 创建一个Promise
        // const myFirstPromise = new Promise((resolve, reject) => {

        // })

        // function myAsyncFunction(url){
        //     return new Promise((resolve, reject) => {
        //         const xhr = new XMLHttpRequest();
        //         xhr.open('GET', url);
        //         xhr.onload = () => resolve(xhr.responseText);
        //         xhr.onerror = () => reject(xhr.statusText);
        //         xhr.send();
        //     })
        // }

        // let myFirstPromise = new Promise(function(resolve, reject){
        //     setTimeout(function(){
        //         resolve('成功！');
        //     }, 250);
        // })

        // myFirstPromise.then(function(successMessage){
        //     console.log('Yay! ' + successMessage);
        // })

        // https://juejin.cn/post/6892555927770103822#heading-29
        // 一、Promise初探
        // console.log(Promise);

        // function getData(){
        //     const p = new Promise((resolve, reject) => {
        //         setTimeout(() => {
        //             console.log('数据获取成功');
        //             resolve('传入成功的数据');
        //         }, 1000);
        //     })
        //     return p;
        // }
        // getData().then((res) => {
        //     console.log(res);
        // })
        // // 数据获取成功
        // // 传入成功的数据

        // const promise = new Promise((resolve, reject) => {
        //     const number = Math.floor(Math.random() * 10);
        //     if(number > 5){
        //         resolve('大于5');
        //     }else{
        //         reject('小于5');
        //     }
        // })

        // promise.then((res) => {
        //     console.log('成功：', res);
        // }).catch((error) => {
        //     console.log('失败：', error);
        // }).finally(() => {
        //     console.log('不管前面发生了啥，我都会被调用');
        // })

        // const promise = new Promise((resolve, reject) => {
        //     console.log(resolve);   //ƒ () { [native code] }
        //     console.log(reject);    //ƒ () { [native code] }
        // })
        // console.log(promise);   //Promise {<pending>}

        // 1、promise对象是一个构造函数，用来生成Promise实例
        // 2、new Promise()传入一个函数，这个函数可以带2哥参数：resolve和reject
        // 3、resolve的作用就是将Promise对象的状态从“未完成”变成“成功”（pending -> resolved）
        // 4、reject的作用就是将Promise对象的状态从“未完成”变成“失败”（pending -> rejected）
        // 5、在没有执行resolve和reject之前，他们还是pending

        // Promise状态：
        // 3种状态：pending,fulfilled,rejected
        // 如果在new Promise中用了resolve()，那么它会走.then()
        // 如果用的是reject()，那么它走.catch()

        // const promise1 = new Promise((resolve, reject) => {
        //     resolve('成功');
        // })

        // promise1.then((res) => {
        //     console.log('res 1: ', res);
        // }).catch((error) => {
        //     console.log('error 1: ', error);
        // })

        // const promise2 = new Promise((resolve, reject) => {
        //     reject('失败');
        // })

        // promise2.then((res) => {
        //     console.log('res 2: ', res);
        // }).catch((error) => {
        //     console.log('error 2: ', error);
        // })

        // res 1:  成功
        // error 2:  失败

        // Promise的状态一经改变就不能再进行更改
        // const promise = new Promise((resolve, reject) => {
        //     resolve('成功 1');
        //     resolve('失败');
        //     resolve('成功 2');
        // })

        // promise.then((res) => {
        //     console.log('res: ', res);
        // }).catch((err) => {
        //     console.log('err: ', err);
        // })
        // res:  成功 1

        // 二、题库
        // Event Loop执行顺序：
        // 1、一开始整个脚本script作为一个宏任务执行
        // 2、执行过程中，同步代码直接执行，宏任务进入宏任务队列，微任务进入微任务队列
        // 3、当前宏任务执行完出队，检查微任务列表，有则依次执行，直到全部执行完毕
        // 4、执行浏览器ui线程的渲染工作
        // 5、检查是否有web worker任务，有则执行
        // 6、执行完本轮的宏任务，回到步骤2，一次循环，直到宏任务和微任务队列为空

        // 微任务包括：
        // MutationObserver
        // Promise.then()/catch()
        // 以Promise为基础开发的其他技术，例如fetch API
        // v8的垃圾回收过程
        // Node独有的process.nextTick

        // 宏任务包括：
        // script
        // setTimeout
        // setInterval
        // I/O
        // UI rendering

        // const promise = new Promise((resolve, reject) => {
        //     console.log('1');
        //     resolve('2');
        // })

        // setTimeout(() => {
        //     console.log('3');
        // }, 0)

        // promise.then((res) => {
        //     console.log(res);
        // })
        // // 1
        // // 2
        // // 3

        // const promise = new Promise((resolve, reject) => {
        //     console.log('promise');
        // })

        // console.log('1', promise);
        // // promise
        // // 1 Promise {<pending>}

        // const promise = new Promise((resolve, reject) => {
        //     console.log(1);
        //     resolve('success');
        //     console.log(2);
        // })

        // promise.then(() => {
        //     console.log(3);
        // })

        // console.log(4);
        // // 1
        // // 2
        // // 4
        // // 3

        // const promise = new Promise((resolve, reject) => {
        //     console.log(1);
        //     console.log(2);
        // })

        // promise.then(() => {
        //     console.log(3);
        // })

        // console.log(4);
        // // 1
        // // 2
        // // 4

        // const promise1 = new Promise((resolve, reject) => {
        //     console.log('promise1');
        //     resolve('resolve1');
        // })

        // const promise2 = promise1.then(res => {
        //     console.log(res);
        // })

        // console.log('1', promise1);
        // console.log('2', promise2);
        // // promise1
        // // 1 Promise {<fulfilled>: "resolve1"}
        // // 2 Promise {<pending>}
        // // resolve1

        // const fn = () => (new Promise((resolve, reject) => {
        //     console.log(1);
        //     resolve('success');
        // }))

        // fn().then(res => {
        //     console.log(res);
        // })

        // console.log('start');
        // // 1
        // // start
        // // success

        // const fn = () => {
        //     return new Promise((resolve, reject) => {
        //         console.log(1);
        //         resolve('success');
        //     })
        // }

        // console.log('start');

        // fn().then(res => {
        //     console.log(res);
        // })

        // // start
        // // 1
        // // success

        // for(var i = 0; i < 3; i++){
        //     setTimeout(() => {
        //         console.log(i);
        //     }, 0)
        // }
        // // 3
        // // 3
        // // 3

        // // 解决方案一：设置立即执行函数
        // for(var i = 0; i < 3; i++){
        //     (function(i){
        //         setTimeout(() => {
        //             console.log(i);
        //         }, 0)
        //     })(i);
        // }
        // // 0
        // // 1
        // // 2

        // // 解决方案二：设置let
        // for(let i = 0; i < 3; i++){
        //     setTimeout(() => {
        //         console.log(i);
        //     }, 0)
        // }
        // // 0
        // // 1
        // // 2

        // console.log('start');

        // setTimeout(() => {
        //     console.log('time');
        // })

        // Promise.resolve().then(() => {
        //     console.log('resolve');
        // })

        // console.log('end');
        // // start
        // // end
        // // resolve
        // // time

        // const promise = new Promise((resolve, reject) => {
        //     console.log(1);

        //     setTimeout(() => {
        //         console.log('timestart');
        //         resolve('success');
        //         console.log('timeend');
        //     })

        //     console.log(2);
        // })

        // promise.then(res => {
        //     console.log(res);
        // })

        // console.log(4);
        // // 1
        // // 2
        // // 4
        // // timestart
        // // timeend
        // // success

        // setTimeout(() => {
        //     console.log('timer1');
        //     setTimeout(() => {
        //         console.log('timer3');
        //     }, 0)
        // }, 0)

        // setTimeout(() => {
        //     console.log('timer2');
        // }, 0)

        // console.log('start');
        // // start
        // // timer1
        // // timer2
        // // timer3

        // setTimeout(() => {
        //     console.log('timer1');
        //     Promise.resolve().then(() => {
        //         console.log('promise');
        //     })
        // }, 0)

        // setTimeout(() => {
        //     console.log('timer2');
        // }, 0)

        // console.log('start');
        // // start
        // // timer1
        // // promise
        // // timer2

        // Promise.resolve().then(() => {
        //     console.log('promise1');
        //     const timer2 = setTimeout(() => {
        //         console.log('timer2');
        //     }, 0)
        // })

        // const timer1 = setTimeout(() => {
        //     console.log('timer1');
        //     Promise.resolve().then(() => {
        //         console.log('promise2');
        //     })
        // }, 0)

        // console.log('start');
        // // start
        // // promise1
        // // timer1
        // // promise2
        // // timer2

        // const promise1 = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         resolve('success');
        //     }, 0)
        // })

        // const promise2 = promise1.then(() => {
        //     throw new Error('error!');
        // })

        // console.log('promise1-1', promise1);
        // console.log('promise2-1', promise2);

        // setTimeout(() => {
        //     console.log('promise1-2', promise1);
        //     console.log('promise2-2', promise2);
        // }, 0)
        // // promise1-1 Promise {<pending>}
        // // promise2-1 Promise {<pending>}
        // // promise1-2 Promise {<fulfilled>: "success"}
        // // promise2-2 Promise {<rejected>: Error: error!

        // const promise1 = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         resolve('success');
        //         console.log('timer1');
        //     }, 0)

        //     console.log('promise1 里面的内容');
        // })

        // const promise2 = promise1.then(() => {
        //     throw new Error('error!');
        // })

        // console.log('promise1-1', promise1);
        // console.log('promise2-1', promise2);

        // setTimeout(() => {
        //     console.log('timer2');
        //     console.log('promise1-2', promise1);
        //     console.log('promise2-2', promise2);
        // }, 0)

        // // promise1 里面的内容
        // // promise1-1 Promise {<pending>}
        // // promise2-1 Promise {<pending>}
        // // timer1
        // // timer2
        // // promise1-2 Promise {<fulfilled>: "success"}
        // // promise2-2 Promise {<rejected>: Error: error!

        // const promise1 = new Promise((resolve, reject) => {
        //     resolve('1');
        // })

        // promise1.then(res => {
        //     console.log('res： ', res);
        // }, err => {
        //     console.log('err： ', err);
        // })

        // const promise2 = new Promise((resolve, reject) => {
        //     reject('1');
        // })

        // promise2.then(res => {
        //     console.log('res： ', res);
        // }, err => {
        //     console.log('err： ', err);
        // })
        // // res：  1
        // // err：  1

        // Promise.resolve(1).then(res1 => {
        //     console.log('res 1: ', res1);
        //     return res1;
        // }).then(res2 => {
        //     console.log('res 2: ', res2);
        // })
        // // res 1:  1
        // // res 2:  1

        // const red = () => {
        //     return new Promise((resolve, reject) => {
        //         setTimeout(() => {
        //             console.log('红');
        //             resolve('红灯走完了');
        //         }, 1000)
        //     })
        // }

        // const green = () => {
        //     return new Promise((resolve, reject) => {
        //         setTimeout(() => {
        //             console.log('绿');
        //             resolve('绿灯走完了');
        //         }, 1000)
        //     })
        // }

        // red().then(res1 => {
        //     console.log('res1: ', res1);
        //     return green();
        // }).then(res2 => {
        //     console.log('res2: ', res2);
        // })

        // // .then()的第2个参数和.catch()作用是一样的
        // const getRandom = new Promise((resolve, reject) => {
        //     const number = Math.random() * 10;
        //     if(number > 5){
        //         reject('数字超过5');
        //     }else{
        //         resolve('数字小于5');
        //     }
        // })

        // // getRandom.then(res => {
        // //     console.log('res: ', res);
        // // }).catch(error => {
        // //     console.log('error: ', error);
        // // })

        // getRandom.then(res => {
        //     console.log('res: ', res);
        // }, error => {
        //     console.log('error: ', error);
        // })

        // const promise = new Promise((resolve, reject) => {
        //     const number = Math.random() * 10;
        //     if(number > 5){
        //         reject('数字超过5');
        //     }else{
        //         resolve('数字小于5');
        //     }
        // })
        
        // promise.then(res => {
        //     console.log('成功： ', res);
        // }).catch(error => {
        //     console.log('失败： ', error);
        // }).finally(() => { 
        //     console.log('不管前面发生了啥，我都会被调用');
        // })

        // const promise = new Promise((resolve, reject) => {
        //     resolve('success1');
        //     reject('error');
        //     resolve('success2');
        // })

        // promise.then(res => {
        //     console.log('then1: ', res);
        // }).then(res => {
        //     console.log('then2: ', res);
        // }).catch(error => {
        //     console.log('catch: ', error);
        // })
        // // then1:  success1
        // // then2:  undefined

        // const promise = new Promise((resolve, reject) => {
        //     reject('error');
        //     resolve('success2');
        // })

        // promise.then(res => {
        //     console.log('then1: ', res);
        // }).then(res => {
        //     console.log('then2: ', res);
        // }).catch(error => {
        //     console.log('catch: ', error);
        // }).then(res => {
        //     console.log('then3: ', res);
        // })
        // // catch:  error
        // // then3:  undefined

        // Promise.resolve(1).then(res => {
        //     console.log(res);
        //     return 2;
        // }).catch(err => {
        //     return 3;
        // }).then(res => {
        //     console.log(res);
        // })
        // // 1
        // // 2

        // Promise.reject(1).then(res => {
        //     console.log(res);
        //     return 2;
        // }).catch(err => {
        //     console.log(err);
        //     return 3;
        // }).then(res => {
        //     console.log(res);
        // })
        // // 1
        // // 3

        // const promise = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         console.log('timer');
        //         resolve('success');
        //     }, 0)
        // })

        // const start = Date.now();

        // promise.then(res => {
        //     console.log(res, Date.now() - start);
        // })

        // promise.then(res => {
        //     console.log(res, Date.now() - start);
        // })
        // // timer
        // // success 13
        // // success 14

        // Promise.resolve().then(() => {
        //     return new Error('error!');
        // }).then(res => {
        //     console.log('then: ', res);
        // }).catch(err => {
        //     console.log('catch: ', err);
        // })
        // // then:  Error: error!

        // const promise = Promise.resolve().then(() => {
        //     return promise;
        // })

        // promise.catch(err => {
        //     console.log(err);
        // })
        // // TypeError: Chaining cycle detected for promise #<Promise>

        // Promise
        //     .resolve(1)
        //     .then(2)
        //     .then(Promise.resolve(3))
        //     .then(console.log)
        // // 1

        // // then和catch的参数希望是函数，传入非函数会发生值透传

        // Promise
        //     .reject('err')
        //     .then(res => {
        //         console.log('success: ', res);
        //     }, err => {
        //         console.log('error: ', err);
        //     }).catch(err => {
        //         console.log('catch: ', err);
        //     })
        // // error:  err

        // Promise
        //     .resolve()
        //     .then(res => {
        //         throw new Error('error!');
        //     }, err => {
        //         console.log('error: ', err);
        //     }).catch(err => {
        //         console.log('catch: ', err);
        //     })
        // // catch:  Error: error!

        // Promise
        //     .resolve('1')
        //     .then(res => {
        //         console.log(res);
        //     }).finally(() => {
        //         console.log('finally1')
        //     })

        // Promise
        //     .resolve('2')
        //     .finally(() => {
        //         console.log('finally2')
        //         return '这里是finally2';
        //     })  
        //     .then(res => {
        //         console.log('finally2 后面的 then 函数', res)
        //     })
        // // 1
        // // finally1
        // // finally2
        // // finally2 后面的 then 函数 2

        // Promise
        //     .resolve('1')
        //     .finally(() => {
        //         console.log('finally1');
        //         return new Error('我是 finally1 中抛出的异常');
        //     })
        //     .then(res => {
        //         console.log('finally 后面的 then 函数：', res);
        //     }).catch(err => {
        //         console.log('捕获错误：', err);
        //     })
        //     // finally1
        //     // finally 后面的 then 函数： 1

        // function promise1(){
        //     let p = new Promise(resolve => {
        //         console.log('promise1');
        //         resolve('1');
        //     })
        //     return p;
        // }

        // function promise2(){
        //     return new Promise((resolve, reject) => {
        //         reject('error');
        //     })
        // }

        // promise1().then(res => {
        //     console.log(res);
        // }).catch(err => {
        //     console.log(err);
        // }).finally(() => {
        //     console.log('finally1');
        // })

        // promise2().then(res => {
        //     console.log(res);
        // }).catch(err => {
        //     console.log(err);
        // }).finally(() => {
        //     console.log('finally2');
        // })

        // // promise1
        // // 1
        // // error
        // // finally1
        // // finally2

        // function promise1(){
        //     let p = new Promise(resolve => {
        //         console.log('promise1');
        //         resolve('1');
        //     })
        //     return p;
        // }

        // function promise2(){
        //     return new Promise((resolve, reject) => {
        //         reject('error');
        //     })
        // }

        // promise1().then(res => {
        //     console.log(res);
        // }).catch(err => {
        //     console.log(err);
        // }).then(() => {
        //     console.log('then1');
        // })

        // promise2().then(res => {
        //     console.log(res);
        // }).catch(err => {
        //     console.log(err);
        // }).then(() => {
        //     console.log('then2');
        // })
        // // promise1
        // // 1
        // // promise1
        // // then1
        // // then2

        // const one = new Promise(resolve => {
        //     setTimeout(() => {
        //         console.log('one');
        //         resolve('one');
        //     }, 1000)
        // })
        
        // const two = new Promise(resolve => {
        //     setTimeout(() => {
        //         console.log('two');
        //         resolve('two');
        //     }, 3000)
        // })

        // const three = new Promise(resolve => {
        //     setTimeout(() => {
        //         console.log('three');
        //         resolve('three');
        //     }, 2000)
        // })
        
        // Promise.all([one, two, three]).then(res => {
        //     console.log(res);
        // })
        // // one
        // // three
        // // two
        // // ["one", "two", "three"]

        // function runAsync(x){
        //     const p = new Promise((resolve, reject) => {
        //         if(x % 2 === 0){
        //             return setTimeout(() => {
        //                 console.log(x);
        //                 resolve(x)
        //             }, 2000);
        //         }
        //         return setTimeout(() => {
        //             console.log(x);
        //             resolve(x)
        //         }, 1000);
        //     })
        //     return p;
        // }

        // Promise.all([
        //     runAsync(1),
        //     runAsync(2),
        //     runAsync(3)
        // ]).then(res => {
        //     console.log(res);
        // })
        // // 1
        // // 3
        // // 2
        // // [1, 2, 3]

        // async function async1(){
        //     console.log(1);
        //     await async2();
        //     console.log(2);
        // }

        // async function async2(){
        //     console.log(3);
        // }

        // async1();

        // console.log(4);
        // // 1
        // // 3
        // // 4
        // // 2

        // async function async1(){
        //     console.log('async');

        //     new Promise(resolve => {
        //         console.log('promise');
        //         resolve();
        //     }).then(res => {
        //         console.log('promise.then');
        //     })
        // }

        // async1();

        // console.log('start');
        // // async
        // // promise
        // // start
        // // promise.then

        // async function async1(){
        //     console.log('async1 start');    //直接执行1
        //     setTimeout(() => {              //宏1
        //         console.log('time1 start');
        //     }, 0);
        //     Promise.resolve().then(res => { //微1
        //         console.log('promise1');
        //     })
        //     await async2();                 //遇到await，下面的代码先阻塞，马后炮1
        //     setTimeout(() => {
        //         console.log('time1 end');   //宏3
        //     }, 0);
        //     console.log('async1 end');
        // }

        // async function async2(){
        //     setTimeout(() => {              //宏2
        //         console.log('time2');
        //     }, 0);
        //     Promise.resolve().then(res => { //微2
        //         console.log('promise2');
        //     })
        //     console.log('async2');          //直接执行2
        // }

        // async1();

        // console.log('start');
        // // async1 start
        // // async2
        // // start
        // // promise1
        // // promise2
        // // async1 end
        // // time1 start
        // // time2
        // // time1 end

        // async function async1(){
        //     console.log('async1 start');    //直接执行1
        //     await async2();                 //马后炮
        //     console.log('async1 end');      //直接执行4
        //     setTimeout(() => {              //宏3
        //         console.log('timer1');
        //     }, 0);
        // }

        // async function async2(){
        //     setTimeout(() => {
        //         console.log('timer2');      //宏1
        //     }, 0)
        //     console.log('async2');          //直接执行2
        // }

        // async1();

        // setTimeout(() => {
        //     console.log('timer3');          //宏2
        // }, 0)

        // console.log('start');               //直接执行3
        // // async1 start
        // // async2
        // // start
        // // async1 end
        // // timer2
        // // timer3
        // // timer1

        // async function fn(){
        //     return 123;
        // }

        // fn().then(res => {
        //     console.log(res);
        // })
        // // 123
        // // 分析：
        // // 正常情况下，async中的await命令是一个Promise对象，返回该对象的结果
        // // 但如果不是Promise对象的话，就会直接返回对应的值，相当于Promise.resolve();

        // async function async1(){
        //     console.log('async1 start');        //直接执行2
        //     await new Promise(resolve => {  
        //         console.log('promise1');        //直接执行3
        //     })
        //     console.log('async1 success');      //马后炮
        //     return 'async1 end';
        // }

        // console.log('script start');            //直接执行1

        // async1().then(res => {
        //     console.log('res: ', res);          //微1
        // })

        // console.log('script end');              //直接执行4
        // // script start
        // // async1 start
        // // promise1
        // // script end
        // // 分析：
        // // 在await后面的Promise是没有返回值的，所以await会一直等待
        // // 这样的话，async1 success后面的内容都不会执行了

        // async function async1(){
        //     console.log('async1 start');    //直接执行2
        //     await new Promise(resolve => {  
        //         console.log('promise1');    //直接执行3
        //         resolve('promise resolve');    
        //     })
        //     console.log('async1 success');  //后面的任务丢入微1
        //     return 'async1 end';            //碰到return告知后面添加一个微2
        // }

        // console.log('script start');        //直接执行1    

        // async1().then(res => {
        //     console.log('res: ', res);      //微2
        // })

        // new Promise(resolve => {
        //     console.log('promise2');        //直接执行4
        //     setTimeout(() => {              //宏1
        //         console.log('timer');
        //     }, 0);
        // })
        // // script start
        // // async1 start
        // // promise1
        // // promise2
        // // async1 success
        // // res: async1 end
        // // timer

        // async function async1(){
        //     console.log('async1 start');    //直接执行2
        //     await async2();                 //async2无返回，后面将一直等待
        //     console.log('async1 end');
        // }

        // async function async2(){
        //     console.log('async2');          //直接执行3
        // }

        // console.log('script start');        //直接执行1

        // setTimeout(() => {
        //     console.log('timeout');         //宏1
        // }, 0)

        // async1();

        // new Promise(resolve => {
        //     console.log('promise1');         //直接执行4
        //     resolve();
        // }).then(res => {
        //     console.log('promise2');         //微1
        // })

        // console.log('script end');          //直接执行5
        // // script start
        // // async1 start
        // // async2
        // // promise1
        // // script end
        // // async1 end(注意：这里也会执行，why？)
        // // promise2
        // // timeout

        // async function async1(){
        //     console.log('async1 start');    //直接执行2
        //     await async2();
        //     console.log('async1 end');      //微1
        // }

        // async function async2(){
        //     console.log('async2');          //直接执行3
        // }

        // console.log('script start');        //直接执行1

        // setTimeout(() => {
        //     console.log('setTimeout');      //宏1
        // }, 0)

        // async1();

        // new Promise(resolve => {
        //     console.log('promise1');        //直接执行4
        //     resolve();
        // }).then(res => {
        //     console.log('promise2');        //微2
        // })

        // console.log('script end');          //直接执行5
        // // script start
        // // async1 start
        // // async2
        // // promise1
        // // script end
        // // async1 end
        // // promise2
        // // setTimeout

        // async function testSomething(){
        //     console.log('test something');     //直接执行2
        //     return 'test something';
        // }

        // async function testAsync(){
        //     console.log('test async');
        //     return Promise.resolve('hello test async');
        // }

        // async function test(){
        //     console.log('test start');          //直接执行1

        //     const v1 = await testSomething();   //后面都是微1-1
        //     console.log('v1: ', v1);            

        //     const v2 = await testAsync();       //后面都是微2-1
        //     console.log('v2: ', v2);
        // }

        // test();

        // const promise = new Promise(resolve => {
        //     console.log('promise start');       //直接执行3
        //     resolve('promise');
        // })

        // promise.then(val => {
        //     console.log(val);                   //微1-2
        // })

        // console.log('test end');                //直接执行4
        // // test start
        // // test something
        // // promise start
        // // test end
        // // v1: test something
        // // test async
        // // promise
        // // v2: hello test async
        
        // async function async1(){
        //     await async2();
        //     console.log('async1');
        //     return 'async1 success';
        // }

        // async function async2(){
        //     return new Promise((resolve, reject) => {
        //         console.log('async2');
        //         reject('error');
        //     })
        // }

        // async1().then(res => {
        //     console.log('res: ', res);
        // })
        // // async2
        // // Uncaught (in promise) error
        // // 分析：如果在async函数中抛出了错误，则种植错误结果，不会继续向下执行。throw new Error也是如此

        // const first = () => (new Promise((resolve1, reject1) => {
        //     console.log(3);                 //直接执行1

        //     const p = new Promise((resolve2, reject2) => {
        //         console.log(7);             //直接执行2

        //         setTimeout(() => {          //宏1
        //             console.log(5);
        //             resolve1(6);
        //             console.log(p);
        //         }, 0)

        //         resolve2(1);                
        //     })
            
        //     p.then(res1 => {
        //         console.log('res1: ', res1); //微1-1
        //     })
        // }))

        // first().then(res2 => {
        //     console.log('res2: ', res2);     //微2-1
        // })

        // console.log(4);                      //直接执行3
        // // 3
        // // 7
        // // 4
        // // res1: 1
        // // 5
        // // Promise {<fulfilled>: 1}
        // // res2: 6

        // const async1 = async() => {
        //     console.log('async1');        //直接执行2  

        //     setTimeout(() => {
        //         console.log('timer1');      //宏1
        //     }, 2000)

        //     await new Promise(resolve => {
        //         console.log('promise1');    //直接执行3
        //     })

        //     console.log('async1 end');      //上面Promise没有resolve所以倒是后面不能执行
        //     return 'async1 success';
        // }

        // console.log('script start');        //直接执行1

        // async1().then(res1 => {
        //     console.log('res1: ', res1);    //微2
        // })

        // console.log('script end');          //直接执行4

        // Promise
        //     .resolve(1)
        //     .then(2)
        //     .then(Promise.resolve(3))
        //     .catch(4)                       
        //     .then(res2 => {
        //         console.log('res1: ', res2);
        //     })

        // setTimeout(() => {                  //宏2
        //     console.log('timer2');
        // }, 1000)
        // // script start
        // // async1
        // // promise1
        // // script end
        // // res1:  1
        // // timer2
        // // timer1
        // // 做错了！！！

        // const p1 = new Promise(resolve => {
        //     setTimeout(() => {          //宏1
        //         resolve('resolve3');
        //         console.log('timer1');
        //     }, 0)
        //     resolve('resolve1');    
        //     resolve('resolve2');
        // }).then(res => {
        //     console.log(res);
        //     setTimeout(() => {
        //         console.log(p1);    //宏2
        //     }, 1000)
        // }).finally(res => {
        //     console.log('finally: ', res);
        // })
        // // resolve1
        // // finally:  undefined
        // // timer1
        // // Promise {<fulfilled>: undefined}

        // 大厂题
        // 1、使用Promise实现每隔一秒输出1,2,3
        // 普通实现：
        // const oneToThree = () => {
        //     const arr = [1, 2, 3];
        //     arr.forEach((item, index)=>{
        //         setTimeout(()=>{
        //             console.log(item)
        //             if(index === 2){
        //                 oneToThree();
        //             }
        //         }, (index+1)*1000)
        //     });
        // }

        // oneToThree();

        // 使用Promise实现
        const oneToThree = () => {
            const arr = [1, 2, 3];
            arr.reduce((prev, next) => {
                return prev.then(() => {
                    return new Promise(resolve => {
                        setTimeout(() => {
                            // console.log(next);
                            resolve();
                        }, 1000)
                    })
                })
            }, Promise.resolve())
        }

        oneToThree();
    </script>
</body>
</html>